#!/bin/bash

plasmashell --replace &

# Detect if the session is Wayland
if [ "$XDG_SESSION_TYPE" = "wayland" ]; then
    echo "Detected Wayland session"
    kwin_wayland --replace &
else
    echo "Unknown/X11 session type: $XDG_SESSION_TYPE"
    kwin_x11 --replace &
fi